services:
#    stades_user.example:
#        class: Stades\UserBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]


    sonata.admin.user.user:
        class: Stades\UserBundle\Admin\UserAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Utilisateurs, label: "Utilisateurs" }
        arguments:
            - ~
            - Stades\UserBundle\Entity\User
            - 'SonataAdminBundle:CRUD'